name: "Deployment Workflow"

on:
  release:
    types: [published]

jobs:
  deploy:
    name: "Deploy to Netlify"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jsmrcaga/action-netlify-deploy@v2.4.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_TO_PROD: true
          install_command: yarn install --frozen-lockfile
          build_command: yarn build
        env:
          REACT_APP_API_BASE_URL: https://api-v2.thenolans.io
          REACT_APP_SSO_URL: https://sso.thenolans.io
          REACT_APP_TOKEN_COOKIE_DOMAIN: .thenolans.io
          PACKAGES_TOKEN: ${{ secrets.PACKAGES_TOKEN }}
